/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils */

#ifndef _Included_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
#define _Included_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
#ifdef __cplusplus
extern "C" {
#endif
#undef net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABAIMInstantProperty
#define net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABAIMInstantProperty 0L
#undef net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABEmailProperty
#define net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABEmailProperty 1L
#undef net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABFirstNameProperty
#define net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABFirstNameProperty 2L
#undef net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABFirstNamePhoneticProperty
#define net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABFirstNamePhoneticProperty 3L
#undef net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABICQInstantProperty
#define net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABICQInstantProperty 4L
#undef net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABJabberInstantProperty
#define net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABJabberInstantProperty 5L
#undef net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABLastNameProperty
#define net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABLastNameProperty 6L
#undef net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABLastNamePhoneticProperty
#define net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABLastNamePhoneticProperty 7L
#undef net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABMiddleNameProperty
#define net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABMiddleNameProperty 8L
#undef net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABMiddleNamePhoneticProperty
#define net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABMiddleNamePhoneticProperty 9L
#undef net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABMSNInstantProperty
#define net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABMSNInstantProperty 10L
#undef net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABNicknameProperty
#define net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABNicknameProperty 11L
#undef net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABOrganizationProperty
#define net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABOrganizationProperty 15L
#undef net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABPersonFlags
#define net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABPersonFlags 14L
#undef net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABPhoneProperty
#define net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABPhoneProperty 12L
#undef net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABShowAsCompany
#define net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABShowAsCompany 1LL
#undef net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABShowAsMask
#define net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABShowAsMask 7LL
#undef net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABYahooInstantProperty
#define net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABYahooInstantProperty 13L
#undef net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABMaidenNameProperty
#define net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABMaidenNameProperty 16L
#undef net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABBirthdayProperty
#define net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABBirthdayProperty 17L
#undef net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABBirthdayComponentsProperty
#define net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABBirthdayComponentsProperty 18L
#undef net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABJobTitleProperty
#define net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABJobTitleProperty 19L
#undef net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABHomePageProperty
#define net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABHomePageProperty 20L
#undef net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABURLsProperty
#define net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABURLsProperty 21L
#undef net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABCalendarURIsProperty
#define net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABCalendarURIsProperty 22L
#undef net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABAddressProperty
#define net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABAddressProperty 23L
#undef net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABOtherDatesProperty
#define net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABOtherDatesProperty 24L
#undef net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABOtherDateComponentsProperty
#define net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABOtherDateComponentsProperty 25L
#undef net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABRelatedNamesProperty
#define net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABRelatedNamesProperty 26L
#undef net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABDepartmentProperty
#define net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABDepartmentProperty 27L
#undef net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABInstantMessageProperty
#define net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABInstantMessageProperty 28L
#undef net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABNoteProperty
#define net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABNoteProperty 29L
#undef net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABSocialProfileProperty
#define net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABSocialProfileProperty 30L
#undef net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABTitleProperty
#define net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABTitleProperty 31L
#undef net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABSuffixProperty
#define net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABSuffixProperty 32L
/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    ABPerson_imageData
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_ABPerson_1imageData
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    ABRecord_valuesForProperties
 * Signature: (J[J)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_ABRecord_1valuesForProperties
  (JNIEnv *, jclass, jlong, jlongArray);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    ABRecord_uniqueId
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_ABRecord_1uniqueId
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    setProperty
 * Signature: (Ljava/lang/String;JLjava/lang/String;Ljava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_setProperty
  (JNIEnv *, jclass, jstring, jlong, jstring, jobject);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    removeProperty
 * Signature: (Ljava/lang/String;J)Z
 */
JNIEXPORT jboolean JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_removeProperty
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    foreachPerson
 * Signature: (Ljava/lang/String;Lnet/java/sip/communicator/plugin/addressbook/PtrCallback;)V
 */
JNIEXPORT void JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_foreachPerson
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    kABAIMInstantProperty
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABAIMInstantProperty
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    kABEmailProperty
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABEmailProperty
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    kABFirstNameProperty
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABFirstNameProperty
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    kABFirstNamePhoneticProperty
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABFirstNamePhoneticProperty
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    kABICQInstantProperty
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABICQInstantProperty
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    kABJabberInstantProperty
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABJabberInstantProperty
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    kABLastNameProperty
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABLastNameProperty
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    kABLastNamePhoneticProperty
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABLastNamePhoneticProperty
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    kABMiddleNameProperty
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABMiddleNameProperty
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    kABMiddleNamePhoneticProperty
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABMiddleNamePhoneticProperty
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    kABMSNInstantProperty
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABMSNInstantProperty
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    kABNicknameProperty
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABNicknameProperty
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    kABOrganizationProperty
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABOrganizationProperty
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    kABPersonFlags
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABPersonFlags
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    kABPhoneProperty
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABPhoneProperty
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    kABYahooInstantProperty
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABYahooInstantProperty
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    kABMaidenNameProperty
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABMaidenNameProperty
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    kABBirthdayProperty
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABBirthdayProperty
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    kABBirthdayComponentsProperty
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABBirthdayComponentsProperty
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    kABJobTitleProperty
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABJobTitleProperty
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    kABHomePageProperty
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABHomePageProperty
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    kABURLsProperty
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABURLsProperty
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    kABCalendarURIsProperty
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABCalendarURIsProperty
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    kABAddressProperty
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABAddressProperty
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    kABOtherDatesProperty
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABOtherDatesProperty
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    kABOtherDateComponentsProperty
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABOtherDateComponentsProperty
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    kABRelatedNamesProperty
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABRelatedNamesProperty
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    kABDepartmentProperty
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABDepartmentProperty
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    kABInstantMessageProperty
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABInstantMessageProperty
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    kABNoteProperty
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABNoteProperty
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    kABSocialProfileProperty
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABSocialProfileProperty
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    kABTitleProperty
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABTitleProperty
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    kABSuffixProperty
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABSuffixProperty
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    kABEmailWorkLabel
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABEmailWorkLabel
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    kABEmailHomeLabel
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABEmailHomeLabel
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    kABAddressHomeLabel
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABAddressHomeLabel
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    kABAddressWorkLabel
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABAddressWorkLabel
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    kABPhoneWorkLabel
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABPhoneWorkLabel
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    kABPhoneHomeLabel
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABPhoneHomeLabel
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    kABPhoneMobileLabel
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABPhoneMobileLabel
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    kABPhoneMainLabel
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABPhoneMainLabel
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    kABPhoneWorkFAXLabel
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABPhoneWorkFAXLabel
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    kABInstantMessageServiceAIM
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABInstantMessageServiceAIM
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    kABInstantMessageServiceFacebook
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABInstantMessageServiceFacebook
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    kABInstantMessageServiceGoogleTalk
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABInstantMessageServiceGoogleTalk
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    kABInstantMessageServiceICQ
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABInstantMessageServiceICQ
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    kABInstantMessageServiceJabber
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABInstantMessageServiceJabber
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    kABInstantMessageServiceMSN
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABInstantMessageServiceMSN
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    kABInstantMessageServiceSkype
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABInstantMessageServiceSkype
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    kABInstantMessageServiceYahoo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABInstantMessageServiceYahoo
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    kABAddressStreetKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABAddressStreetKey
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    kABAddressCityKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABAddressCityKey
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    kABAddressZIPKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABAddressZIPKey
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    kABAddressCountryKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_kABAddressCountryKey
  (JNIEnv *, jclass);

JNIEXPORT jboolean JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_deleteContact
  (JNIEnv *jniEnv, jclass clazz, jstring id);

JNIEXPORT jstring JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_createContact
  (JNIEnv *jniEnv, jclass clazz);

JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_getContactPointer
  (JNIEnv *jniEnv, jclass clazz, jstring id);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    start
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_start
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    stop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_stop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils
 * Method:    setDelegate
 * Signature: (JLnet/java/sip/communicator/plugin/addressbook/MacAddressBookUtils/NotificationsDelegate;)V
 */
JNIEXPORT void JNICALL Java_net_java_sip_communicator_plugin_addressbook_MacAddressBookUtils_setDelegate
  (JNIEnv *, jclass, jlong, jobject);


#ifdef __cplusplus
}
#endif
#endif
