// Copyright (c) Microsoft Corporation. All rights reserved.
package net.java.sip.communicator.service.insights;

public enum InsightsEventHint
{
    SIP_MESSAGE_WAITING,
    SIP_INCOMING_CALL,
    SIP_CALL_ENDED,

    JABBER_IM_DELETE_ROSTER_ENTRY,
    JABBER_IM_SEND_MESSAGE,
    JABBER_FILE_TRANSFER,
    JABBER_IM_LOG_IN,

    GUI_CALL_PULL,
    GUI_CALL_PUSH,
    GUI_CALL_ADD,
    GUI_CALL_CRM,
    GUI_CALL_MERGE,
    GUI_CALL_KEYPAD,
    GUI_CALL_SEND_IM,
    GUI_CALL_SWAP,
    GUI_CALL_HOLD,
    GUI_CALL_RECEIVE_VIDEO,
    GUI_CALL_TRANSFER,
    GUI_ENABLE_VIDEO,
    GUI_IM_EXPORT,
    GUI_IM_LEAVE_ROOM,
    GUI_IM_UPDATE_SUBJECT,
    GUI_IM_ADD_PARTICIPANTS,
    GUI_EMERGENCY_CALL_RETRY,
    GUI_USER_PERMISSION,

    CONTACT_LIST_ADD_CONTACT,
    CONTACT_LIST_DELETE_CONTACT,
    CONTACT_SEARCH,
    CONTACT_IM_INSERT,

    DESKTOP_UTIL_SSO_TOKEN,
    DESKTOP_UTIL_EMAIL_COMPOSE,

    GENERAL_CONFIG_PLUGIN_CALLER_ID_SETTING,
    GENERAL_CONFIG_PLUGIN_RINGTONE_SETTING,
    GENERAL_CONFIG_PLUGIN_RINGTONE_IS_DISTINCTIVE,
    GENERAL_CONFIG_PLUGIN_ENABLE_CALL_RATING,
    GENERAL_CONFIG_PLUGIN_OUTGOING_CTD_WITH,
    GENERAL_CONFIG_PLUGIN_OUTGOING_CALL_WITH,
    GENERAL_CONFIG_PLUGIN_ANALYTICS_ENABLED,

    PROVISIONING_LOG_IN,

    PROTOCOL_MEDIA_CALL_MUTE,

    PROTOCOL_MEDIA_CALL_ENDED,
    PROTOCOL_MEDIA_CALL_CONNECTED,

    IM_REMOVE_PARTICIPANT,

    EMERGENCY_CALL_HANDLED_BY_CLIENT,

    APP_TERMINATED,

    CONTACT_SYNC_TO_NATIVE,

    USER_CDAP_CONFIRM_PROVIDER,

    EVENT_CRASH_REPORT,

    COMMON_OUTGOING_CALL_FAILED,
    COMMON_HINT_CONTACT_DELETED
}
