#define IDI_AVAILABLE_ICON                      1
#define IDI_AWAY_ICON                           2
#define IDI_FORWARDING_ICON                     3
#define IDI_DND_ICON                            4
#define IDI_ONTHEPHONE_ICON                     5
#define IDI_OFFLINE_ICON                        6
#define IDI_BUSY_ICON                           7
#define IDI_MEETING_ICON                        8

#define IDI_NOTIFICATIONS_1_ICON                11
#define IDI_NOTIFICATIONS_2_ICON                12
#define IDI_NOTIFICATIONS_3_ICON                13
#define IDI_NOTIFICATIONS_4_ICON                14
#define IDI_NOTIFICATIONS_5_ICON                15
#define IDI_NOTIFICATIONS_6_ICON                16
#define IDI_NOTIFICATIONS_7_ICON                17
#define IDI_NOTIFICATIONS_8_ICON                18
#define IDI_NOTIFICATIONS_9_ICON                19
#define IDI_NOTIFICATIONS_9_PLUS_ICON           20