/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "resource.h"
#include <windows.h>
#include <shobjidl.h>
/* Header for class taskbar */

#ifndef __uuidof
#define __uuidof(i) &i
#endif /* #ifndef __uuidof */

#ifndef _Included_taskbar
#define _Included_taskbar
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL Java_net_java_sip_communicator_service_systray_TaskbarIconOverlay_SetOverlayIcon
	(JNIEnv *, jclass, jint, jstring);

JNIEXPORT jint JNICALL Java_net_java_sip_communicator_service_systray_TaskbarIconOverlay_AlertWindow
	(JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif

HRESULT taskbar_iidFromString(JNIEnv *env, jstring str, LPIID iid);