// Copyright (c) Microsoft Corporation. All rights reserved.
package net.java.sip.communicator.service.database.schemautil;

/**
 * A primary key.
 * <p>
 * We don't expect this to be used externally
 */
public class PrimaryKey extends IntDBColumn
{
    public PrimaryKey(String name)
    {
        super(name);
    }

    @Override
    protected void qualify(StringBuilder sb)
    {
       // See http://hsqldb.org/doc/guide/ch02.html#N104B3
       sb.append(" GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY");
    }
}