/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_java_sip_communicator_plugin_addressbook_OutlookDataHandler */

#ifndef _Included_net_java_sip_communicator_plugin_addressbook_OutlookDataHandler
#define _Included_net_java_sip_communicator_plugin_addressbook_OutlookDataHandler
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_OutlookServerNative
 * Method:    Initialize
 * Signature: (J)V
 */
JNIEXPORT void JNICALL
    Java_net_java_sip_communicator_plugin_addressbook_OutlookServerNative_Initialize
  (JNIEnv *, jclass, jint, jstring, jstring, jstring);

/*
 * Class:     net_java_sip_communicator_plugin_addressbook_OutlookServerNative
 * Method:    MAPIUninitialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_java_sip_communicator_plugin_addressbook_OutlookServerNative_Uninitialize
  (JNIEnv *, jclass);

JNIEXPORT jboolean JNICALL Java_net_java_sip_communicator_plugin_addressbook_OutlookServerNative_CheckServerIsAlive
  (JNIEnv *, jclass);

JNIEXPORT int JNICALL Java_net_java_sip_communicator_plugin_addressbook_OutlookServerNative_getOutlookBitnessVersion
    (JNIEnv *jniEnv, jclass clazz);

JNIEXPORT int JNICALL Java_net_java_sip_communicator_plugin_addressbook_OutlookServerNative_getOutlookVersion
    (JNIEnv *jniEnv, jclass clazz);

#ifdef __cplusplus
}
#endif
#endif
